name    'puppetlabs-xinetd'
version '2.0'
source  'https://github.com/lengau/puppet-xinetd'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Alex Lowe's Xinetd Puppet Module'
description 'Puppet module to configure xinetd services, forked off the potentially abandoned puppetlabs project.'
project_page 'https://github.com/lengau/puppet-xinetd'
